import fs from "node:fs";
import path from "node:path";
import type { MediaAsset } from "@/lib/content/types";

const imageExtensions = ["webp", "jpg", "jpeg", "png", "gif"] as const;

export const profileImageCandidates = [
  // Generated by scripts/optimize-profile.mjs. Preferred because the static
  // export disables Next image optimization, so whatever is listed first is
  // exactly what ships as the home page LCP element.
  "/images/profile/SinaProfile.webp",
  "/images/profile/SinaProfile.png",
  "/images/profile/sina-profile.webp",
  "/images/profile/sina-profile.jpg",
  "/images/profile/sina-profile.jpeg",
  "/images/profile/sina-profile.png",
] as const;

export function getExistingPublicAssetPath(
  candidates: readonly string[],
): string | undefined {
  return candidates.find((candidate) => {
    const relativePath = candidate.replace(/^\/+/, "");
    return fs.existsSync(path.join(process.cwd(), "public", relativePath));
  });
}

export function getProfileImagePath() {
  return getExistingPublicAssetPath(profileImageCandidates);
}

export function getProjectThumbnailMedia(
  slug: string,
  title: string,
): MediaAsset | undefined {
  const src = getExistingPublicAssetPath(
    imageExtensions.map((extension) => `/images/projects/${slug}.${extension}`),
  );

  if (!src) {
    return undefined;
  }

  return {
    alt: `Project thumbnail for ${title}`,
    src,
    type: "image",
  };
}

export type CertificateImageAsset = {
  alt: string;
  caption: string;
  src: string;
};

const certificateImageDirectory = "/images/certificates";

export function getCertificateImageAssets(): CertificateImageAsset[] {
  const directory = path.join(
    process.cwd(),
    "public",
    certificateImageDirectory.replace(/^\/+/, ""),
  );

  if (!fs.existsSync(directory)) {
    return [];
  }

  return fs
    .readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((fileName) => {
      const extension = path.extname(fileName).replace(".", "").toLowerCase();
      return imageExtensions.includes(
        extension as (typeof imageExtensions)[number],
      );
    })
    .sort((a, b) => a.localeCompare(b))
    .map((fileName) => {
      const caption = humanizeAssetName(fileName);
      return {
        alt: `Award or certificate image: ${caption}`,
        caption,
        src: `${certificateImageDirectory}/${fileName}`,
      };
    });
}

function humanizeAssetName(fileName: string) {
  return path
    .basename(fileName, path.extname(fileName))
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
